language: java
jdk:
  - oraclejdk8
sudo: false
script: "mvn cobertura:cobertura"
notifications:
  email:
    recipients:
      - casales.ignacio@gmail.com
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)