-- Create the database.
-- create database restmess_db;

-- Create the user.
-- create user 'app_usr_restmsg'@'localhost' identified by 'vat8ucru';

-- Give all the privileges to the new user on the newly created database.
-- grant all on restmess_db.* to 'app_usr_restmsg'@'localhost';

-- revoke all on restmess_db.* from 'app_usr_restmsg'@'localhost';

-- This gives the application only the privileges to make changes to only the data of the database.
-- grant select, insert, delete, update on restmess_db.* to 'app_usr_restmsg'@'localhost';

-- USE restmess_db;

-- The Schema itself is auto-generated by Hibernate.
